untitled2/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_view
from django.urls import path
from . import views
from .forms import LoginForm


app_name = "accounts"

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(success_url='/'), name='login', kwargs={'authentication_form': LoginForm}),
    url(r'^register/$',views.ResterView.as_view(success_url='/'),name='register')
    # url(r'^register/$', views.RegisterView.as_view(success_url="/"), name='register'),
    # url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    # path(r'account/result.html', views.account_result, name='result')
]

untitled2/untitled2/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('accounts.urls', namespace='account')),
]

untitled2/accounts/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now

class BlogUser(AbstractUser):
    nickname = models.CharField('昵称', max_length=100, blank=True)
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)
    source = models.CharField("创建来源", max_length=100, blank=True)
    def __str__(self):
        return self.email

untitled2/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.forms import widgets



class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = widgets.TextInput(attrs={'placeholder': "username", "class": "form-control"})
        self.fields['password'].widget = widgets.PasswordInput(
            attrs={'placeholder': "password", "class": "form-control"})

    def clean(self):
        cleaned_data = super().clean()

        username = cleaned_data.get('name',None)
        password = cleaned_data('password',None)
        if len(username)>len(password):
            self.add_error('username','自定义的 错误')


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget = widgets.TextInput(attrs={'placeholder': "username", "class": "form-control"})
        self.fields['email'].widget = widgets.EmailInput(attrs={'placeholder': "email", "class": "form-control"})
        self.fields['password1'].widget = widgets.PasswordInput(
            attrs={'placeholder': "password", "class": "form-control"})
        self.fields['password2'].widget = widgets.PasswordInput(
            attrs={'placeholder': "repeat password", "class": "form-control"})

    def clean_email(self):
        email =self.cleaned_data['email']
        if get_user_model().objects.filter(email = email).exists():
            raise ValidationError('邮箱已经存在')
        return email
    class Meta:
        model = get_user_model()
        fields = ("username", "email")

untitled2/accounts/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.views.generic import FormView


from .forms import LoginForm,RegisterForm

class LoginView(FormView):
    form_class = LoginForm
    template_name = 'accounts/login.html'
    success_url = '/'


    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        #  当 校验错误的 时候
        return self.render_to_response(self.get_context_data(form=form))


    def form_valid(self, form):
        #  当 校验正确的时候
        return HttpResponseRedirect(self.get_success_url())

    # def form_valid(self, form):
    #     """If the form is valid, redirect to the supplied URL."""
    #     return HttpResponseRedirect(self.get_success_url())
    #
    # def form_invalid(self, form):
    #     """If the form is invalid, render the invalid form."""
    #     return self.render_to_response(self.get_context_data(form=form))


class ResterView(FormView):
    form_class = RegisterForm
    template_name = 'accounts/registration_form.html'
    def form_valid(self, form):
        if form.is_valid():
            user = form.save(False)
            user.is_active = False
            user.source = 'Register'
            user.save(True)
            return HttpResponseRedirect('/')
        else:
            return self.render_to_response({
                'form': form
            })

untitled2/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<form action="{% url 'account:login' %}"  method="post">
      {% csrf_token %}
        {{ form.non_field_errors }}
      {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                {% endfor %}

                <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
{#	<fieldset>#}
{#		<legend align="center">用户登录</legend></br>#}
{#		<label>用户名：</label>#}
{#		<input type="text"  id="user">(请输入用户名)</br></br>#}
{#		<label>密&nbsp&nbsp码：</label>#}
{#		<input type="password"  id="pwd1">（输入密码）<br><br>#}
{#		<input type="submit" name="" value="提交" >#}
{#	</fieldset>#}
</form>


</body>
</html>

untitled2/templates/accounts/registration_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>




	<form action="{% url 'account:register' %}" method="post">
	 {% csrf_token %}
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                {% endfor %}

     <button class="btn btn-lg btn-primary btn-block" type="submit">Create Your Account</button>
</form>

</body>
</html>